# Generated by Django 5.0.6 on 2024-06-29 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattigame',
            old_name='state',
            new_name='status',
        ),
    ]
